import Navbar from '@/components/Navbar';
import '@/app/globals.css';
import { Metadata } from 'next';
import Head from 'next/head';
import { HeroHighlight } from '@/components/ui/Hero-Highlight';

export const metadata: Metadata = {
  title: "Mansher Singh | Portfolio",
  description: "Generated by create next app",
};

export default function MyApp({ Component, pageProps }: any) {
  return (
    <>
      <Head>
        <title>Mansher | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logoLeo.png" />
      </Head>
      <div className="w-full bg-black-100">
        <div className="inset-0">
        <Navbar />
        <HeroHighlight containerClassName="min-h-screen flex flex-col">
        <Component {...pageProps} />
        </HeroHighlight>
        </div>
      </div>
    </>
  );
}
