import Navbar from '@/components/Navbar';
import '@/app/globals.css';
import { Metadata } from 'next';
import Head from 'next/head';

export const metadata: Metadata = {
  title: "Mansher Singh | Portfolio",
  description: "Generated by create next app",
};

export default function MyApp({ Component, pageProps }: any) {
  return (
    <>
      <Head>
        <title>Mansher | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logoLeo.png" />
      </Head>
      <div className="relative w-full h-screen bg-black-100">
        <div className="absolute inset-0 z-10">
        <Navbar />
        <Component {...pageProps} />
        </div>
      </div>
    </>
  );
}
