import Navbar from "@/components/Navbar";
import "@/app/globals.css";
import { Metadata } from "next";
import Head from "next/head";
import { HeroHighlight } from "@/components/ui/hero-highlight";

export const metadata: Metadata = {
	title: "Mansher Singh | Portfolio",
	description: "Generated by create next app",
};

export default function MyApp({ Component, pageProps }: any) {
	return (
		<>
			<Head>
				<title>Mansher Singh | Portfolio</title>
				<meta name="description" content="Generated using Next.js" />
				<link rel="icon" href="/logoLeo.png" />
			</Head>
			<div className="w-full bg-black-100">
				<div className="inset-0">
					<Navbar />
					<HeroHighlight containerClassName="min-h-screen flex flex-col">
						<Component {...pageProps} />
					</HeroHighlight>
				</div>
			</div>
		</>
	);
}
